### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by rainbyte**

### CODE REVIEW

**Comment by stefonarch** [comment]
Thank you for the work, but all translations get imported from poeditor. at next import it would be overwritten... just sign up here:
https://poeditor.com/join/project/cnSZa85DRN

**Comment by rainbyte** [comment]
I have updated some there, but other ones seems to not be present. I will try again, you can close this.

**Comment by stefonarch** [comment]
I guess we didn't import them in 3.7... but next version coming soon sure.

**Comment by rainbyte** [comment]
Already updated there :)

**Pull request closed without merging**
